host: server.mineunity.eu
port: 3306
database: Mineunity48
username: Mineunity48
password: password
unlock_stages:
  0: 'Darf man Spammen, Beleidigen, etc.? (Ja/Nein)'
  1: 'Dürfen Bugs ausgenutzt werden? (Ja/Nein)'
  2: 'Ist Griefen erlaubt? (Ja/Nein)'
  3: 'Darf man Hack-Clients benutzen? (Ja/Nein)'
unlock_stages_answer:
  0: 'nein'
  1: 'nein'
  2: 'ja'
  3: 'nein'