main: ch.gyselanimatioon.miepcraft.Main
name: Miepcraft
author: GyselAnimatioon
version: 1.0

commands:
  fixxp:
    usage: /fixxp
    description: Setzt die XP Kosten des Items in deiner Hand zurueck
  fixitem:
    usage: /fixitem
    description: Repariert das Item deiner Hand
  ticket:
    usage:  /ticket [add|list] <opt args>
    description: Tickets hinzufuegen und abfragen
  list:
    usage:  /list
    description: Listet Online Spieler auf
  tp:
    usage:  /tp [User]
    description: Teleportiert dich zu einem Spieler.
    
permissions:
  miepcraft.commands.ticket.list:
    description: Ticket liste anzeigen permissions
    default: op
  miepcraft.listener.command.spy:
    description: command spy permissions
    default: op
  miepcraft.commands.tp:
    description: tp permissions
    default: op